# Generated by Django 3.0.6 on 2020-05-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='최대 100자 내로 입력가능합니다.', max_length=100),
        ),
    ]
